theme: jekyll-theme-slate
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Patrícia Paula's portfolio
description: 

show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
